
services:
  backend:
    image: "ghcr.io/mcgillrocketteam/groundstation-backend-2025:master"
    build:
      context: "https://github.com/McGillRocketTeam/groundstation-backend-2025.git"
    hostname: localhost
    container_name: yamcs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 30s
    volumes:
      - yamcs-telemetry:/yamcs/gs_backend/yamcs-data
    privileged: true
    ports:
      - "8090:8090"
      - "10015:10015/udp"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    network_mode: host
  frontend:
    image: "ghcr.io/mcgillrocketteam/groundstation-frontend-v2:main"
    build:
      context: "https://github.com/McGillRocketTeam/groundstation-frontend-v2.git"
    ports:
      - "80:80"
    depends_on:
      - backend
      - mongodb
    networks:
      - quickstart



  mongodb:
    image: mongo:6.0
    container_name: mongodb
    hostname: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: admin
    volumes:
        - mongodb_data:/data/db
    networks:
      - quickstart

networks:
  quickstart:
    driver: bridge
volumes:
  yamcs-telemetry:
  mongodb_data:
    driver: local
